package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * AppUser generated by hbm2java
 */
public class AppUser  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private boolean accountExpired;
     private boolean accountLocked;
     private String address;
     private String city;
     private String country;
     private String postalCode;
     private String province;
     private boolean credentialsExpired;
     private String email;
     private Boolean accountEnabled;
     private String firstName;
     private String lastName;
     private String password;
     private String passwordHint;
     private String phoneNumber;
     private String username;
     private String website;
     private Set roles = new HashSet(0);

    public AppUser() {
    }

	
    public AppUser(boolean accountExpired, boolean accountLocked, boolean credentialsExpired, String email, String firstName, String lastName, String password, String username) {
        this.accountExpired = accountExpired;
        this.accountLocked = accountLocked;
        this.credentialsExpired = credentialsExpired;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.username = username;
    }
    public AppUser(boolean accountExpired, boolean accountLocked, String address, String city, String country, String postalCode, String province, boolean credentialsExpired, String email, Boolean accountEnabled, String firstName, String lastName, String password, String passwordHint, String phoneNumber, String username, String website, Set roles) {
       this.accountExpired = accountExpired;
       this.accountLocked = accountLocked;
       this.address = address;
       this.city = city;
       this.country = country;
       this.postalCode = postalCode;
       this.province = province;
       this.credentialsExpired = credentialsExpired;
       this.email = email;
       this.accountEnabled = accountEnabled;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.passwordHint = passwordHint;
       this.phoneNumber = phoneNumber;
       this.username = username;
       this.website = website;
       this.roles = roles;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public boolean isAccountExpired() {
        return this.accountExpired;
    }
    
    public void setAccountExpired(boolean accountExpired) {
        this.accountExpired = accountExpired;
    }
    public boolean isAccountLocked() {
        return this.accountLocked;
    }
    
    public void setAccountLocked(boolean accountLocked) {
        this.accountLocked = accountLocked;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public boolean isCredentialsExpired() {
        return this.credentialsExpired;
    }
    
    public void setCredentialsExpired(boolean credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getAccountEnabled() {
        return this.accountEnabled;
    }
    
    public void setAccountEnabled(Boolean accountEnabled) {
        this.accountEnabled = accountEnabled;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPasswordHint() {
        return this.passwordHint;
    }
    
    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }




}


