package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0



/**
 * CaseClassesId generated by hbm2java
 */
public class CaseClassesId  implements java.io.Serializable {


     private int caseClassId;
     private String caseCode;

    public CaseClassesId() {
    }

    public CaseClassesId(int caseClassId, String caseCode) {
       this.caseClassId = caseClassId;
       this.caseCode = caseCode;
    }
   
    public int getCaseClassId() {
        return this.caseClassId;
    }
    
    public void setCaseClassId(int caseClassId) {
        this.caseClassId = caseClassId;
    }
    public String getCaseCode() {
        return this.caseCode;
    }
    
    public void setCaseCode(String caseCode) {
        this.caseCode = caseCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaseClassesId) ) return false;
		 CaseClassesId castOther = ( CaseClassesId ) other; 
         
		 return (this.getCaseClassId()==castOther.getCaseClassId())
 && ( (this.getCaseCode()==castOther.getCaseCode()) || ( this.getCaseCode()!=null && castOther.getCaseCode()!=null && this.getCaseCode().equals(castOther.getCaseCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCaseClassId();
         result = 37 * result + ( getCaseCode() == null ? 0 : this.getCaseCode().hashCode() );
         return result;
   }   


}


