package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Claims generated by hbm2java
 */
public class Claims  implements java.io.Serializable {


     private Integer claimId;
     private String claim;
     private String claimsCaseCode;
     private String claimDescription;
     private Set clientses = new HashSet(0);

    public Claims() {
    }

	
    public Claims(String claim, String claimsCaseCode) {
        this.claim = claim;
        this.claimsCaseCode = claimsCaseCode;
    }
    public Claims(String claim, String claimsCaseCode, String claimDescription, Set clientses) {
       this.claim = claim;
       this.claimsCaseCode = claimsCaseCode;
       this.claimDescription = claimDescription;
       this.clientses = clientses;
    }
   
    public Integer getClaimId() {
        return this.claimId;
    }
    
    public void setClaimId(Integer claimId) {
        this.claimId = claimId;
    }
    public String getClaim() {
        return this.claim;
    }
    
    public void setClaim(String claim) {
        this.claim = claim;
    }
    public String getClaimsCaseCode() {
        return this.claimsCaseCode;
    }
    
    public void setClaimsCaseCode(String claimsCaseCode) {
        this.claimsCaseCode = claimsCaseCode;
    }
    public String getClaimDescription() {
        return this.claimDescription;
    }
    
    public void setClaimDescription(String claimDescription) {
        this.claimDescription = claimDescription;
    }
    public Set getClientses() {
        return this.clientses;
    }
    
    public void setClientses(Set clientses) {
        this.clientses = clientses;
    }




}


