package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ClientFinance generated by hbm2java
 */
public class ClientFinance  implements java.io.Serializable {


     private Integer clientFinanceId;
     private int clientId;
     private Integer caseId;
     private String receiptCode;
     private Long amountPaid;
     private Date datePaid;
     private Integer paidTo;

    public ClientFinance() {
    }

	
    public ClientFinance(int clientId) {
        this.clientId = clientId;
    }
    public ClientFinance(int clientId, Integer caseId, String receiptCode, Long amountPaid, Date datePaid, Integer paidTo) {
       this.clientId = clientId;
       this.caseId = caseId;
       this.receiptCode = receiptCode;
       this.amountPaid = amountPaid;
       this.datePaid = datePaid;
       this.paidTo = paidTo;
    }
   
    public Integer getClientFinanceId() {
        return this.clientFinanceId;
    }
    
    public void setClientFinanceId(Integer clientFinanceId) {
        this.clientFinanceId = clientFinanceId;
    }
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public Integer getCaseId() {
        return this.caseId;
    }
    
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }
    public String getReceiptCode() {
        return this.receiptCode;
    }
    
    public void setReceiptCode(String receiptCode) {
        this.receiptCode = receiptCode;
    }
    public Long getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(Long amountPaid) {
        this.amountPaid = amountPaid;
    }
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    public Integer getPaidTo() {
        return this.paidTo;
    }
    
    public void setPaidTo(Integer paidTo) {
        this.paidTo = paidTo;
    }




}


