package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private Integer clientId;
     private Claims claims;
     private Persons persons;
     private String party1;
     private String party2;
     private String party3;
     private Date dateOfRegistration;
     private String notes;
     private int creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private Boolean retired;
     private Integer retiredBy;
     private Date dateRetired;
     private String retireReason;
     private String uuid;

    public Clients() {
    }

	
    public Clients(Claims claims, Persons persons, String party1, String party2, Date dateOfRegistration, int creator, Date dateCreated, String uuid) {
        this.claims = claims;
        this.persons = persons;
        this.party1 = party1;
        this.party2 = party2;
        this.dateOfRegistration = dateOfRegistration;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public Clients(Claims claims, Persons persons, String party1, String party2, String party3, Date dateOfRegistration, String notes, int creator, Date dateCreated, Integer changedBy, Date dateChanged, Boolean retired, Integer retiredBy, Date dateRetired, String retireReason, String uuid) {
       this.claims = claims;
       this.persons = persons;
       this.party1 = party1;
       this.party2 = party2;
       this.party3 = party3;
       this.dateOfRegistration = dateOfRegistration;
       this.notes = notes;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.retired = retired;
       this.retiredBy = retiredBy;
       this.dateRetired = dateRetired;
       this.retireReason = retireReason;
       this.uuid = uuid;
    }
   
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
    public Claims getClaims() {
        return this.claims;
    }
    
    public void setClaims(Claims claims) {
        this.claims = claims;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public String getParty1() {
        return this.party1;
    }
    
    public void setParty1(String party1) {
        this.party1 = party1;
    }
    public String getParty2() {
        return this.party2;
    }
    
    public void setParty2(String party2) {
        this.party2 = party2;
    }
    public String getParty3() {
        return this.party3;
    }
    
    public void setParty3(String party3) {
        this.party3 = party3;
    }
    public Date getDateOfRegistration() {
        return this.dateOfRegistration;
    }
    
    public void setDateOfRegistration(Date dateOfRegistration) {
        this.dateOfRegistration = dateOfRegistration;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public Boolean getRetired() {
        return this.retired;
    }
    
    public void setRetired(Boolean retired) {
        this.retired = retired;
    }
    public Integer getRetiredBy() {
        return this.retiredBy;
    }
    
    public void setRetiredBy(Integer retiredBy) {
        this.retiredBy = retiredBy;
    }
    public Date getDateRetired() {
        return this.dateRetired;
    }
    
    public void setDateRetired(Date dateRetired) {
        this.dateRetired = dateRetired;
    }
    public String getRetireReason() {
        return this.retireReason;
    }
    
    public void setRetireReason(String retireReason) {
        this.retireReason = retireReason;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


