package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0



/**
 * DocumentsId generated by hbm2java
 */
public class DocumentsId  implements java.io.Serializable {


     private int documentId;
     private String documentSerial;

    public DocumentsId() {
    }

    public DocumentsId(int documentId, String documentSerial) {
       this.documentId = documentId;
       this.documentSerial = documentSerial;
    }
   
    public int getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(int documentId) {
        this.documentId = documentId;
    }
    public String getDocumentSerial() {
        return this.documentSerial;
    }
    
    public void setDocumentSerial(String documentSerial) {
        this.documentSerial = documentSerial;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentsId) ) return false;
		 DocumentsId castOther = ( DocumentsId ) other; 
         
		 return (this.getDocumentId()==castOther.getDocumentId())
 && ( (this.getDocumentSerial()==castOther.getDocumentSerial()) || ( this.getDocumentSerial()!=null && castOther.getDocumentSerial()!=null && this.getDocumentSerial().equals(castOther.getDocumentSerial()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDocumentId();
         result = 37 * result + ( getDocumentSerial() == null ? 0 : this.getDocumentSerial().hashCode() );
         return result;
   }   


}


