package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * EmpExpenditure generated by hbm2java
 */
public class EmpExpenditure  implements java.io.Serializable {


     private Integer expId;
     private Integer empId;
     private Integer clientId;
     private Date dateSpent;
     private Long amountOut;
     private String expReceiptCode;
     private Long amountUsed;
     private Integer receivedBy;

    public EmpExpenditure() {
    }

    public EmpExpenditure(Integer empId, Integer clientId, Date dateSpent, Long amountOut, String expReceiptCode, Long amountUsed, Integer receivedBy) {
       this.empId = empId;
       this.clientId = clientId;
       this.dateSpent = dateSpent;
       this.amountOut = amountOut;
       this.expReceiptCode = expReceiptCode;
       this.amountUsed = amountUsed;
       this.receivedBy = receivedBy;
    }
   
    public Integer getExpId() {
        return this.expId;
    }
    
    public void setExpId(Integer expId) {
        this.expId = expId;
    }
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
    public Date getDateSpent() {
        return this.dateSpent;
    }
    
    public void setDateSpent(Date dateSpent) {
        this.dateSpent = dateSpent;
    }
    public Long getAmountOut() {
        return this.amountOut;
    }
    
    public void setAmountOut(Long amountOut) {
        this.amountOut = amountOut;
    }
    public String getExpReceiptCode() {
        return this.expReceiptCode;
    }
    
    public void setExpReceiptCode(String expReceiptCode) {
        this.expReceiptCode = expReceiptCode;
    }
    public Long getAmountUsed() {
        return this.amountUsed;
    }
    
    public void setAmountUsed(Long amountUsed) {
        this.amountUsed = amountUsed;
    }
    public Integer getReceivedBy() {
        return this.receivedBy;
    }
    
    public void setReceivedBy(Integer receivedBy) {
        this.receivedBy = receivedBy;
    }




}


