package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer employeeId;
     private int personId;
     private int jobTitleId;
     private Date dateHired;
     private int jobLocationId;
     private int creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private Boolean retired;
     private Integer retiredBy;
     private Date dateRetired;
     private String retireReason;
     private String uuid;

    public Employees() {
    }

	
    public Employees(int personId, int jobTitleId, Date dateHired, int jobLocationId, int creator, Date dateCreated, String uuid) {
        this.personId = personId;
        this.jobTitleId = jobTitleId;
        this.dateHired = dateHired;
        this.jobLocationId = jobLocationId;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public Employees(int personId, int jobTitleId, Date dateHired, int jobLocationId, int creator, Date dateCreated, Integer changedBy, Date dateChanged, Boolean retired, Integer retiredBy, Date dateRetired, String retireReason, String uuid) {
       this.personId = personId;
       this.jobTitleId = jobTitleId;
       this.dateHired = dateHired;
       this.jobLocationId = jobLocationId;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.retired = retired;
       this.retiredBy = retiredBy;
       this.dateRetired = dateRetired;
       this.retireReason = retireReason;
       this.uuid = uuid;
    }
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }
    public int getJobTitleId() {
        return this.jobTitleId;
    }
    
    public void setJobTitleId(int jobTitleId) {
        this.jobTitleId = jobTitleId;
    }
    public Date getDateHired() {
        return this.dateHired;
    }
    
    public void setDateHired(Date dateHired) {
        this.dateHired = dateHired;
    }
    public int getJobLocationId() {
        return this.jobLocationId;
    }
    
    public void setJobLocationId(int jobLocationId) {
        this.jobLocationId = jobLocationId;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public Boolean getRetired() {
        return this.retired;
    }
    
    public void setRetired(Boolean retired) {
        this.retired = retired;
    }
    public Integer getRetiredBy() {
        return this.retiredBy;
    }
    
    public void setRetiredBy(Integer retiredBy) {
        this.retiredBy = retiredBy;
    }
    public Date getDateRetired() {
        return this.dateRetired;
    }
    
    public void setDateRetired(Date dateRetired) {
        this.dateRetired = dateRetired;
    }
    public String getRetireReason() {
        return this.retireReason;
    }
    
    public void setRetireReason(String retireReason) {
        this.retireReason = retireReason;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


