package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0



/**
 * Locations generated by hbm2java
 */
public class Locations  implements java.io.Serializable {


     private Integer locationId;
     private String location;

    public Locations() {
    }

    public Locations(String location) {
       this.location = location;
    }
   
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


