package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons  implements java.io.Serializable {


     private Integer personId;
     private Date dateOfBirth;
     private String gender;
     private int creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private Integer retiredBy;
     private boolean voided;
     private String uuid;
     private Set personNames = new HashSet(0);
     private Set personAddresses = new HashSet(0);
     private Set personAttributes = new HashSet(0);
     private Set clientses = new HashSet(0);
     private Set clientses_1 = new HashSet(0);

    public Persons() {
    }

	
    public Persons(Date dateOfBirth, String gender, int creator, Date dateCreated, boolean voided) {
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.voided = voided;
    }
    public Persons(Date dateOfBirth, String gender, int creator, Date dateCreated, Integer changedBy, Date dateChanged, Integer retiredBy, boolean voided, String uuid, Set personNames, Set personAddresses, Set personAttributes, Set clientses, Set clientses_1) {
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.retiredBy = retiredBy;
       this.voided = voided;
       this.uuid = uuid;
       this.personNames = personNames;
       this.personAddresses = personAddresses;
       this.personAttributes = personAttributes;
       this.clientses = clientses;
       this.clientses_1 = clientses_1;
    }
   
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public Integer getRetiredBy() {
        return this.retiredBy;
    }
    
    public void setRetiredBy(Integer retiredBy) {
        this.retiredBy = retiredBy;
    }
    public boolean isVoided() {
        return this.voided;
    }
    
    public void setVoided(boolean voided) {
        this.voided = voided;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getPersonNames() {
        return this.personNames;
    }
    
    public void setPersonNames(Set personNames) {
        this.personNames = personNames;
    }
    public Set getPersonAddresses() {
        return this.personAddresses;
    }
    
    public void setPersonAddresses(Set personAddresses) {
        this.personAddresses = personAddresses;
    }
    public Set getPersonAttributes() {
        return this.personAttributes;
    }
    
    public void setPersonAttributes(Set personAttributes) {
        this.personAttributes = personAttributes;
    }
    public Set getClientses() {
        return this.clientses;
    }
    
    public void setClientses(Set clientses) {
        this.clientses = clientses;
    }
    public Set getClientses_1() {
        return this.clientses_1;
    }
    
    public void setClientses_1(Set clientses_1) {
        this.clientses_1 = clientses_1;
    }




}


