package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PersonName generated by hbm2java
 */
public class PersonName  implements java.io.Serializable {


     private Integer personNameId;
     private Persons persons;
     private String prefix;
     private String givenName;
     private String middleName;
     private String familyNamePrefix;
     private String familyName;
     private String familyName2;
     private String familyNameSuffix;
     private int creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private Integer retiredBy;
     private String uuid;

    public PersonName() {
    }

	
    public PersonName(Persons persons, int creator, Date dateCreated) {
        this.persons = persons;
        this.creator = creator;
        this.dateCreated = dateCreated;
    }
    public PersonName(Persons persons, String prefix, String givenName, String middleName, String familyNamePrefix, String familyName, String familyName2, String familyNameSuffix, int creator, Date dateCreated, Integer changedBy, Date dateChanged, Integer retiredBy, String uuid) {
       this.persons = persons;
       this.prefix = prefix;
       this.givenName = givenName;
       this.middleName = middleName;
       this.familyNamePrefix = familyNamePrefix;
       this.familyName = familyName;
       this.familyName2 = familyName2;
       this.familyNameSuffix = familyNameSuffix;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.retiredBy = retiredBy;
       this.uuid = uuid;
    }
   
    public Integer getPersonNameId() {
        return this.personNameId;
    }
    
    public void setPersonNameId(Integer personNameId) {
        this.personNameId = personNameId;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    public String getGivenName() {
        return this.givenName;
    }
    
    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getFamilyNamePrefix() {
        return this.familyNamePrefix;
    }
    
    public void setFamilyNamePrefix(String familyNamePrefix) {
        this.familyNamePrefix = familyNamePrefix;
    }
    public String getFamilyName() {
        return this.familyName;
    }
    
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }
    public String getFamilyName2() {
        return this.familyName2;
    }
    
    public void setFamilyName2(String familyName2) {
        this.familyName2 = familyName2;
    }
    public String getFamilyNameSuffix() {
        return this.familyNameSuffix;
    }
    
    public void setFamilyNameSuffix(String familyNameSuffix) {
        this.familyNameSuffix = familyNameSuffix;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public Integer getRetiredBy() {
        return this.retiredBy;
    }
    
    public void setRetiredBy(Integer retiredBy) {
        this.retiredBy = retiredBy;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


