package org.vetech.lrms.core.models;
// Generated Jan 17, 2015 8:30:18 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Long id;
     private String description;
     private String name;
     private Set appUsers = new HashSet(0);

    public Role() {
    }

    public Role(String description, String name, Set appUsers) {
       this.description = description;
       this.name = name;
       this.appUsers = appUsers;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAppUsers() {
        return this.appUsers;
    }
    
    public void setAppUsers(Set appUsers) {
        this.appUsers = appUsers;
    }




}


